### ISSUE TITLE
Update for allow for R 4.0+ (and minor plotting function duplication)

### ISSUE THREAD

**Issue by benjaminleroy** [rizbicki/predictionBands#1]
Hi @rizbicki,

1. **Impact of R 4.0**

I noted that both this package and FlexCoDE don't work well under R 4.0, as there was a change with global class functions like `predict` and `plot` in the R 4.0 update (see https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf and search `.S3method`). Basically you need to use the `.S3method` function to notate that you're creating a `method` for your objects.    

I've updated it in my [fork](https://github.com/benjaminleroy/predictionBands/commit/84a2fb88faa7e89a5af70777a66d9fa19f131efd) (and I could make a pull request) - but I figured you might want to know as it appears to affect FlexCoDE as well.

2. **Plotting Function**

Your plotting function produces the same plot 2x from the following lines:
```r
# lines 288 and 289
plot(g) 
return(g)
```
might I recommend either
```r
plot(g)
invisible(g)
```
or not using `plot(g)`?

Thanks
Ben

**Comment by rizbicki** [comment]
@benjaminleroy Many thanks! I'd be happy with a pull request :)
